# Generated by Django 3.0.3 on 2020-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=30)),
                ('heroine', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('budget', models.IntegerField(null=True)),
                ('reldate', models.DateField(null=True)),
            ],
        ),
    ]
