# Generated by Django 3.0.6 on 2020-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('movie_images', models.ImageField(upload_to='albums/')),
                ('actor_name', models.CharField(choices=[('Balakrishna', 'balakrishna'), ('Nargarjuna', 'nargarjuna'), ('Maheshbabu', 'maheshbabu'), ('JrNtr', 'jrNtr'), ('Phrabas', 'phrabas')], max_length=30)),
                ('actress_name', models.CharField(choices=[('Samantha', 'Samantha'), ('Shriya Saran', 'Shriya Saran'), ('Anushka Shetty', 'Anushka Shetty'), ('Tamannaah', 'Tamannaah'), ('Nayanthara', 'Nayanthara'), ("Ileana D'Cruz", "Ileana D'Cruz")], max_length=30)),
                ('director', models.CharField(choices=[('S. S. Rajamouli', 'S. S. Rajamouli'), ('Trivikram Srinivas', 'Trivikram Srinivas'), ('Puri Jagannadh', 'Puri Jagannadh')], max_length=30)),
                ('producer', models.CharField(choices=[('Suresh Babu', 'Suresh Babu'), ('Dasari Narayana Rao', 'Dasari Narayana Rao'), ('Raghavendra Rao', 'Raghavendra Rao')], max_length=30)),
                ('story_line', models.TextField(max_length=2000)),
                ('trailer', models.FileField(upload_to='posters/')),
                ('releasedate', models.DateTimeField(null=True)),
                ('vardict', models.CharField(choices=[('All Time Blockbuster', 'All Time Blockbuster'), ('Blockbuster', 'Blockbuster'), ('superhit', 'superhit'), ('Average', 'Average')], max_length=30)),
            ],
        ),
    ]
