# Generated by Django 3.0.3 on 2020-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
